# Generated by Django 4.1.4 on 2023-02-01 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_orderplaced_status_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='rate',
            new_name='rating',
        ),
    ]
